name: Build VSCode Extension
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18 # https://github.com/docker/setup-qemu-action/tree/v2.1.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@8c0edbc76e98fa90f69d9a2c020dcb50019dc325 # https://github.com/docker/setup-buildx-action/tree/v2.2.1

    - name: Log in to the Container registry
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # https://github.com/docker/login-action/tree/v2.1.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push VSCode Extension
      uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5 # https://github.com/docker/build-push-action/tree/v3.2.0
      with:
        context: '{{defaultContext}}:.kutespaces/extension'
        push: true
        tags: ghcr.io/kutespaces/cdk8s:vscode-extension
